name: medical
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_slider_drawer: ^2.1.2
  geolocator: ^8.0.0
  firebase_core: ^2.24.2
  flutter_map: ^3.1.0
  url_launcher: ^6.1.11
  flutter_layout_grid: ^2.0.0
  fluttertoast: ^8.2.4
  image_picker: ^1.0.2
  lottie: ^2.3.2
  badges: ^3.1.1
  firebase_database: ^10.4.0
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.2.3
  firebase_auth: ^4.16.0
  image_network: ^2.5.2
  maps_launcher: ^2.0.0
  baseflow_plugin_template: ^2.1.2
  latlong2: ^0.8.2
  geocoding: ^3.0.0
  permission_handler: ^11.0.1
  # cloud_firestore: ^4.14.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  photo_view: ^0.14.0
  carousel_slider: ^4.0.0
  device_preview: ^1.1.0
  cloud_firestore: ^4.7.0 
  firebase_storage: ^11.2.0 
  google_fonts: ^3.0.0
  persistent_bottom_nav_bar: ^5.0.0
  get: ^4.6.0
  dropdown_button2: ^2.1.3
  iconsax: ^0.0.8



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lotties_images/
