// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFk-XRa25V8r5dKcBJ9Nb_CbTlUPxEHjs',
    appId: '1:75979297009:web:81548085cf871498365950',
    messagingSenderId: '75979297009',
    projectId: 'medicalapp-988dc',
    authDomain: 'medicalapp-988dc.firebaseapp.com',
    storageBucket: 'medicalapp-988dc.appspot.com',
    measurementId: 'G-9RPW2ZHF4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuOTJdWVwY0dA5-kMv-H6xa3dSJcWRxvs',
    appId: '1:75979297009:android:6a917837b0f3c2a6365950',
    messagingSenderId: '75979297009',
    projectId: 'medicalapp-988dc',
    storageBucket: 'medicalapp-988dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkw7zRtcBsHq8Kj4s07nrWkSv-95OTt4s',
    appId: '1:75979297009:ios:2cb606b69c9b4430365950',
    messagingSenderId: '75979297009',
    projectId: 'medicalapp-988dc',
    storageBucket: 'medicalapp-988dc.appspot.com',
    iosBundleId: 'com.example.medical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkw7zRtcBsHq8Kj4s07nrWkSv-95OTt4s',
    appId: '1:75979297009:ios:2cb606b69c9b4430365950',
    messagingSenderId: '75979297009',
    projectId: 'medicalapp-988dc',
    storageBucket: 'medicalapp-988dc.appspot.com',
    iosBundleId: 'com.example.medical',
  );
}
