// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUerFUvT5td7U8evcnDHRpiL7h9KqxZu8',
    appId: '1:1002122361097:web:597d9c90040834bd8ebbd8',
    messagingSenderId: '1002122361097',
    projectId: 'medical-9c0a9',
    authDomain: 'medical-9c0a9.firebaseapp.com',
    storageBucket: 'medical-9c0a9.appspot.com',
    measurementId: 'G-NQFTC4WXGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB0aS4AlvHUVGRKcdnTrjcN6JgmQiCD20',
    appId: '1:1002122361097:android:8144a69f9bcaf2d08ebbd8',
    messagingSenderId: '1002122361097',
    projectId: 'medical-9c0a9',
    storageBucket: 'medical-9c0a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkQTJ5Ce8-0KS3zX-wbIwFhNic09nrBLs',
    appId: '1:1002122361097:ios:79879ebb43ebdee28ebbd8',
    messagingSenderId: '1002122361097',
    projectId: 'medical-9c0a9',
    storageBucket: 'medical-9c0a9.appspot.com',
    iosBundleId: 'com.example.medical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkQTJ5Ce8-0KS3zX-wbIwFhNic09nrBLs',
    appId: '1:1002122361097:ios:79879ebb43ebdee28ebbd8',
    messagingSenderId: '1002122361097',
    projectId: 'medical-9c0a9',
    storageBucket: 'medical-9c0a9.appspot.com',
    iosBundleId: 'com.example.medical',
  );
}
