// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6c-jyV5Hl0WiNYOf2kY7oP5T0b3SGRwk',
    appId: '1:231588690647:web:a06f5e3996f828729a0e92',
    messagingSenderId: '231588690647',
    projectId: 'medicalfinal-79ade',
    authDomain: 'medicalfinal-79ade.firebaseapp.com',
    storageBucket: 'medicalfinal-79ade.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA63ovp_w5fGumk5C_Wo-QvQvmmAG6ZAEA',
    appId: '1:231588690647:android:de612ebc04b03d859a0e92',
    messagingSenderId: '231588690647',
    projectId: 'medicalfinal-79ade',
    storageBucket: 'medicalfinal-79ade.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiZ7uHD9j9W6Ho0N554iUDT5ZGuwWeocw',
    appId: '1:231588690647:ios:2c50f578264c05d49a0e92',
    messagingSenderId: '231588690647',
    projectId: 'medicalfinal-79ade',
    storageBucket: 'medicalfinal-79ade.appspot.com',
    iosBundleId: 'com.example.medical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiZ7uHD9j9W6Ho0N554iUDT5ZGuwWeocw',
    appId: '1:231588690647:ios:2c50f578264c05d49a0e92',
    messagingSenderId: '231588690647',
    projectId: 'medicalfinal-79ade',
    storageBucket: 'medicalfinal-79ade.appspot.com',
    iosBundleId: 'com.example.medical',
  );
}
